### ISSUE TITLE
Different coverage report uploaded in scout

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/scout#778] opened 2018-03-26 13:44 UTC
When uploading a family in Scout, one can get two different values in the coverage reports on the different level of coverage.

For example if clicking on the "View report" in Scout, the values for the different coverage depth will be shown. If the URL link is copied and pasted in a new tab, all values will change and totally new coverage values will been shown. The same appear for the covered transcripts. See attached files

[Twist50M_lower_cov.pdf](https://github.com/Clinical-Genomics/scout/files/1848033/Twist50M_lower_cov.pdf)
[Twist50M.pdf](https://github.com/Clinical-Genomics/scout/files/1848034/Twist50M.pdf)

**Comment by northwestwitch** [comment] 2018-03-26 14:52
I've found the reason why the report seems to acts weird. Whenever you click on the coverage report button from scout you pass a gene list to chanjo_report and this list is used to calculate the coverage I guess. See the first figure: there's a lot of genes passed to the page for panel 1. 

<img width="984" alt="screenshot_0" src="https://user-images.githubusercontent.com/28093618/37913442-29d4bab2-3115-11e8-88ea-89548cde66dc.png">

When you refresh the page the list is not passed and in fact there are no genes for panel 1. See what it is passed on this other screenshot:

<img width="1186" alt="screenshot_1" src="https://user-images.githubusercontent.com/28093618/37913509-4d4e2d70-3115-11e8-989d-ea965d6eaf00.png">

The coverage numbers are different because in the first case the coverage is calculated on the passed genes, but after the refreshing the statistics are on something else.

It's quite easy to fix I think but the problem is that we don't have chanjo_report among our repositories so we have to fork it, modify it and re-install it on the server. A bit of a hassle but I'll work on it!

**Comment by northwestwitch** [comment] 2018-03-27 13:43
I have fixed the issue, now I just have to know where I should I do the pull request: on our forked chanjo-report repository on clinical genomics (see the new branch), or the original. See here: https://github.com/robinandeer/chanjo-report/issues/29  .

**Comment by northwestwitch** [comment] 2018-03-28 09:56
There is a problem with the release version of chanjo-report running on clinical-db. The installed version is in fact version 3.0.something while the updated one is 4. The fix I wrote does not apply to the old version at all so this bug is not fixable until we do a major upgrade of chanjo-report (and scout?). We'll fix it but for the time being keep in mind that if you are interested on the coverage on the specific genes of the panel(s) then you should only trust the report produced by the button in scout. Do not refresh the page (from the browser) or copy the URL to another browser tab and most importantly don't share the link in emails and so on. If you need to send or save coverage reports download the PDF from the scout side panel.

**Comment by moonso** [comment] 2018-04-18 08:57
@northwestwitch can we close this since it is chanjo-related and not scout-related?

**Comment by northwestwitch** [comment] 2018-04-19 02:45
Yes, I'm closing it!

**Closed by northwestwitch** 2018-04-19 02:45 UTC
Labels: Easy, bug
