### ISSUE TITLE
Cannot access "matching causatives from other cases"

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2838] opened 2021-09-01 06:47 UTC
Hi! 

As the title says, in scout cancer I cannot access the previous cases who have matching causatives. I get this error message: 

![image](https://user-images.githubusercontent.com/62098218/131624880-a1e152e2-dcec-4283-966d-d2dc3c82bc69.png)

I hope someone can help :) 

Hälsningar HEro

**Comment by northwestwitch** [comment] 2021-09-01 06:51
Hi @heronikdin, thanks for reporting the problem. this is a bug we are aware of and we have already fixed, see #2826 and #2827.

As soon as we install a new Scout release (hopefully this week) this will be fixed. Apologies!

**Comment by dnil** [comment] 2021-09-01 06:52
Right, that was reported in #2826 and fixed in #2827! It will appear with the next fix release, possibly this week.

**Comment by northwestwitch** [comment] 2021-09-01 06:53
Closing this PR as it's a duplicate of #2826

**Closed by northwestwitch** 2021-09-01 06:53 UTC
