### ISSUE TITLE
Germline tag on cancer variants, inherited and tumor/normal

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1240] opened 2019-06-12 08:04 UTC
Add a tag to variant if it is identified by germline variant caller. This highly is relevant for inherited cancer cases where we have family/trios.

**Comment by hassanfa** [comment] 2019-06-12 13:13
Adding comment for future me:

- In non-inherited cancers and somatic variant filtering, we need to make sure we get rid of noise and possible germline mutations. This can be mitigated by using a matching normal sample and inhouse panel of normals.

- For inherited cancers, we need to remember not to filter out germline variants, but add a tag.

Now, VCF INFO field can hold a tag with possible germline.

**Comment by dnil** [comment] 2020-09-11 12:15
Very nice comments to future self. Does he need any help? If so just post the keys in question and intended behaviour and we can try to add it and corresponding tests! 😊

**Comment by hassanfa** [comment] 2020-09-11 12:19
This is a tough problem to solve. I was a bit naive when proposed this.

Case of normal germline, normal somatic, and tumor somatic is not easy to dissect.

For now this is done within balsamic and filtering, but hard to add it to Scout without a proper study.

Let's close it until need rises again.

**Comment by dnil** [comment] 2020-09-11 12:38
Ok! If you don't want to load the INFO-tag, we could also keep this open and await cases with multiple kinds of analyses? If we had both a cancer and an RD germline analysis, it would be easy to flag the germline variants that reappear on the cancer view? 
That said I dont actually see why someone would not have run it as a tumor-normal pair then. So we close?

**Comment by hassanfa** [comment] 2020-09-11 12:42
I have never been big fan of hard thresholds. Since there AF filter for Normal and Tumor, it is a better filter than just removing a variant because it is found in normal...

**Comment by hassanfa** [comment] 2020-09-11 12:43
👨🏽‍⚖️ : close!

**Closed** 2020-09-11 12:43 UTC
Labels: Cancer, Easy, enhancement
