### ISSUE TITLE
Re-upload misses added VCFs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4228] opened 2023-11-24 08:23 UTC
On a recently rerun case (`quicktapir`), added VCFs since last MIP version (MEI) were found missing. They are present in the CG-generated scout load config, so presumably the issue is with scout load.

**Comment by dnil** [comment] 2023-11-24 08:24
I'm going to manually load the VCFs for the case in question on this case, but should be possible to reproduce locally.

**Comment by northwestwitch** [comment] 2023-11-24 13:23
Was it research variants that were missing or both clinical and research?

**Comment by dnil** [comment] 2023-11-24 13:37
Both for MEI:

![Screenshot 2023-11-24 at 08 48 36](https://github.com/Clinical-Genomics/scout/assets/758570/f7c59095-df1c-481f-9d17-d97815ed1e2f)

<img width="855" alt="Screenshot 2023-11-24 at 09 51 33" src="https://github.com/Clinical-Genomics/scout/assets/758570/8aa19577-27e9-4dc2-a054-15c0662df948">

**Comment by northwestwitch** [comment] 2023-11-24 14:03
I can't seem to reproduce locally on the demo file? What I'm doing is:

- Commenting out the mei-related VCF files line
- Loading the case with `scout setup demo`
- Mei clinical variants are not loaded and path is missing from case document (as it should be)

Then:

- Un-comment the mei lines on config file
- `scout --demo load case scout/demo/643594.config.yaml --update --keep-actions`
- mei clinical variants are present (as I would expect). Research variants are not shown because it's not a `is_research` case.

🤔

**Comment by dnil** [comment] 2023-11-24 14:35
Interesting?! Some interaction with the research? Sounds odd. Have you checked the working load command against what the cg app is using?

**Comment by dnil** [comment] 2023-11-24 14:38
How about the pydantic idea - case loaded with old pre pydantic change, without mei, then load with current?

**Comment by northwestwitch** [comment] 2023-11-24 15:06
We checked other cases re-runned lately and couldn't find any other similar case. For instance [this one](https://scout.scilifelab.se/cust002/F0010402) loaded one day before is fine

**Comment by northwestwitch** [comment] 2023-11-24 15:13
The weird thing is that the upload date for the case in question is one year old:

<img width="468" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/afc8f9ac-bf6a-448b-a756-6aadb6a216d0">

**Comment by northwestwitch** [comment] 2023-11-28 07:11
Shall we close this one, we can re-open if it happens again?

**Closed** 2023-11-28 08:37 UTC
Labels: bug
