### ISSUE TITLE
Scout demo database doesn't load Ancestry (pred.) or Parenthood

### ISSUE THREAD

**Issue by leahkemp** [Clinical-Genomics/scout#1989] opened 2020-07-22 03:51 UTC
Hi all, thankyou for the great software!

I'm having loading some values into scout that should be included through these variables/files in the config file:

```yaml
peddy_ped: scout/demo/643594.peddy.ped
peddy_ped_check: scout/demo/643594.ped_check.csv
peddy_sex_check: scout/demo/643594.sex_check.csv
```

When the demo database is loaded, scout doesn't appear to be grabbing the values from these files to populate the Ancestry (pred.) and Parenthood columns of the 'Individuals' panel in the 643594 case (see images below):

![scout_parenthood_loading](https://user-images.githubusercontent.com/46519743/88131992-6699ad80-cc32-11ea-85dd-b4e8cb1c0ccf.PNG)
![scout_parenthood_loading_2](https://user-images.githubusercontent.com/46519743/88131995-67cada80-cc32-11ea-93c0-48037444dd22.PNG)

- No error messages are thrown when creating or serving the database.

- I'm using scout version 4.19 and python 3.7.6 installed within a conda environment.

Please let me know if you require any further details from me, thanks in advance for your help!

**Comment by northwestwitch** [comment] 2020-07-22 06:09
Hi Leah, 
we really appreciate that you are using our software!
I think that in the 3 years that I've been working with Scout I haven't loaded a single case using the peddy files. What we do in general is providing the pedigree info in the config file and use that instead. You can load the demo case using the config by running: 'scout setup demo'. 

I'm sorry that the documentation is not more clear about using using the peddy files, and of course if you have this option it should work. I'll take a look at it in mid August, as soon as I'm back from my vacation.

**Comment by leahkemp** [comment] 2020-07-23 03:33
Hi @northwestwitch, thanks for the speedy reply!

Just to clarify, loading peddy files through `peddy_ped:`, `peddy_ped_check:` and `peddy_sex_check:` in a config file doesn't currently work?

**Some background:**

The reason I tried loading `peddy_ped`, `peddy_ped_check` and `peddy_sex_check` with the demo database when I opened this issue was because I'm attempting to include this information in scout for our clinical database.

**For our clinical database:**

Passing peddy files to `peddy_ped:`, `peddy_ped_check:` and `peddy_sex_check:` in a config file following [scout docs - load config](http://www.clinicalgenomics.se/scout/admin-guide/load-config/) seems to populate the Ancestry (pred.) column as shown in the picture below:

![scout_example](https://user-images.githubusercontent.com/46519743/88248806-8a262c00-ccf6-11ea-9eaf-b51fa3ef5568.PNG)

This appears to be successfully populated by grabbing these values from the ancestry column in `Trio_DHB4177.peddy.ped`. However parenthood is not populated from `Trio_DHB4177.ped_check.csv` or `Trio_DHB4177.sex_check.csv` (see the values provided by these files below:)

*Trio_DHB4177.ped_check.csv*

![scout_ped_check](https://user-images.githubusercontent.com/46519743/88248970-1d5f6180-ccf7-11ea-9a27-1d99796e102c.PNG)

*Trio_DHB4177.sex_check.csv*

![scout_sex_check](https://user-images.githubusercontent.com/46519743/88248974-20f2e880-ccf7-11ea-8cd5-674ce6cd45f9.PNG)

In the past, our group was getting information on parental status - so those peddy files have been 'linking' correctly in the past. We also vaguely remember (not 100% sure) that scout would include a neat little tick/cross marker that would pop up beside the male/female symbols in the 'Sex' column that would indicate whether peddy "agreed" or "disagreed" with sexes that were assigned in the config file.

Including these pedigree/sex checks into scout is an important feature for our group to ensure these sanity checks are reported in our workflow, so we are hoping to get this feature working.

Thanks for your help!

**Comment by northwestwitch** [comment] 2020-08-11 06:17
I've checked our cases in production and ancestry, parenthood and sex check work for us when the files are provided in the config file. Must be some error in the demo files. I'll compare your ped_check and sex_check files with ours.

**Comment by northwestwitch** [comment] 2020-08-11 09:11
Hi again @leahkemp , I've found out what the problem is.

The command `scout setup demo` at the moment doesn't load the peddy info (thanks for opening the issue!), but this will be fixed in the next Scout release (later thin month).


The workaround for the demo case (or your clinical cases) is:
Rename 2 fields in the config file:
- peddy_ped_check --> peddy_check
- peddy_sex_check --> peddy_sex

And then load the demo case with the command `scout --demo load case scout/demo/643594.config.yaml`

The command for one of your own cases would be `scout (--demo) load case path/to/your/config/file`

This way it should work. I'm going to fix the naming of these fields also in the documentation. Sorry for the inconvenience, and thanks again for your feedback!

**Closed** 2020-08-11 09:33 UTC

**Comment by leahkemp** [comment] 2020-08-11 22:54
Fantastic the workaround has worked perfectly for our clinical data! Many thanks for your help @northwestwitch!
