### ISSUE TITLE
Genotyping wrong?

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#780] opened 2018-04-05 13:43 UTC
https://scout.scilifelab.se/cust002/F0001621/eb3195743b234c53c9833e3a61067258

According to GT call 210-1-1A is heterozygous - but when I look at alignment it seems that 210-2-1U is a carrier....????

Is something wrong with the analysis?

**Comment by dnil** [comment] 2018-04-05 15:01
Looks scary.. Family presumably ok as confirmed e.g. by inheritance on X and parenthood test. 
The variant is only displayed for FreeBayes - is that were something went sour?

**Comment by moonso** [comment] 2018-04-06 06:05
Hmm it certainly looks wrong... I can not understand why not all variant callers called 210-2-1U??
Do you have any idea @henrikstranneheim ?

**Comment by moonso** [comment] 2018-04-06 08:36
Hi, ok me and @vwirta have done a small investigation now and this is going to be very technical.
I think that this problem has occurred during the splitting of the original VCF. If that is true we really need to take some action because then the splitting does not work as expected.

When we look in the VCF there are 3 different variations, 2 on position 6458993 and 1 on 6458994, this is most probably a result of breaking down(splitting) a multi allelic call in the original VCF.

Variant calls looks like this:

 Sample/GT | T/C | TA/CG | A/G
------- | ---- | ------ | -----
210-1-1A | 0/0 | 0/1 | 0/0
210-2-1U | 0/1 | 0/0 | 0/1
210-2-2U | 0/0 | 0/0 | 0/0

I think we have to look at the unsplitted VCF to get to the bottom with this. Is that possible @henrikstranneheim ? Maybe we can run the variant calling only with mip?

**Comment by moonso** [comment] 2018-04-20 06:59
So @henrikstranneheim has traced the issue back to freebayes where for some positions freebayes mixes the individual genotype calls. This is terrible of course and we need to investigate further when and why this happens. 

Fortunately GATK and samtools does not do this so the correct variant is present in our data, we will NOT miss anything.

Well spotted @KickiLagerstedt 😸 

Closing here since this is not a scout issue

**Closed by moonso** 2018-04-20 06:59 UTC
Labels: Under discussion, question
