### ISSUE TITLE
ACMG/AMP for the classification page.

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#1616] opened 2020-01-14 09:06 UTC
From https://github.com/Clinical-Genomics/scout/issues/1460

**Comment by moonso** [comment] 2020-02-05 11:47
- Cancer ACMG/AMP different from ACMG for classification of variants
- Pre-fill ACMG/AMP if possible, when possible. Is it feasible.

**Comment by northwestwitch** [comment] 2020-02-18 14:51
I could start with this. Do we want a semi-automated classification system where you click buttons as we have for rare variants?

**Comment by northwestwitch** [comment] 2020-02-18 15:04
I've found this:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5707196/

Is it the official one?

**Comment by dnil** [comment] 2020-04-23 06:49
This appears to be a duplicate of #1241, but the thread is a bit meatier here. I'll close the old one.

**Comment by northwestwitch** [comment] 2020-07-07 07:46
@mikaell this is a nice and useful new feature we were planning to have in Scout. You could take a look at it if you feel inspired. It's a complex one where you have to do the reading and develop something similar to the ACMG variant classification  (manual and automated) we have for the rare diseases cases, but for cancer.

**Comment by mikaell** [comment] 2020-07-07 12:13
I'll see what I can do.

**Comment by mikaell** [comment] 2020-07-08 08:58
I've started to do some reading on the subject.

However –the implementation task is -at least for me- vague. Is it possible to explain in detail:
* What needs to be done? 
* What infrastructure is already available?

**Comment by northwestwitch** [comment] 2020-07-08 09:21
That's why I wrote it's a complex one! 😄
As you know, until not so long ago Scout was meant to solve rare diseases and not cancer. The official way to classify variants in rare diseases as  pathogenic, likely pathogenic, uncertain significance (VUS), benign and likely benign is the [ACMG classification](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4544753/). 

In scout, on the variant page there are 2 ways to classify variants:

![image](https://user-images.githubusercontent.com/28093618/86900607-d32d8c00-c10b-11ea-8043-1b09182dcc75.png)

- manual classification, that is clicking on one of the colored buttons above.
- guided classifications, in the page that opens when you click on "classify".

Manual classification is quite easy and relies on an arbitrary decision made by the user. Guided classification is based on a decision-making algorithm that mirrors the guidelines of the ACMG paper (code is under scout/utils/acmg.py).

The problem is cancer variants are not classified using the ACMG criteria, but using another document. I've found this document, that I think is the official one: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5707196/

The idea is to create an alternative model to classify variants in cancer cases using a model from this latter article, instead of the ACMG one.

**Comment by dnil** [comment] 2020-07-08 09:45
I seem recall adding the manual part for Tier-classifications at one point. This would be about the second part - a guided page similar to the rare disorder one. With semi-automatic presets as an optional bonus for when it looks too simple. Eg the “rare” criteria could be automatically checked in the decision page if frequency criteria allow. Compare an other old issue for the rare disorders as well that I believe @moonso has an unmerged version of.

**Comment by northwestwitch** [comment] 2020-07-08 09:52
Oh yes, the variant tier is there @dnil: 
![image](https://user-images.githubusercontent.com/28093618/86904560-2f46df00-c111-11ea-8798-f59186b1d34e.png)

This PR should be about the guided classification. The algorithm can be exactly the same as the ACMG I guess, but the categories (form options) are different, and based on the other article.

**Comment by hassanfa** [comment] 2020-07-08 10:10
What is the different between variant tag vs ACMG? I think we can remove ACMG completely for cancer view and rely on variant tags, no?

**Comment by northwestwitch** [comment] 2020-07-08 10:11
> What is the different between variant tag vs ACMG? I think we can remove ACMG completely for cancer view and rely on variant tags, no?

I think so

**Comment by hassanfa** [comment] 2020-07-08 11:11
I say, lets nuke ACMG for cancer view.

**Comment by dnil** [comment] 2023-01-16 15:39
If I got this correctly, it is being used slightly off-specification by at least one site, and it doesn't really hurt more than perhaps distracting from the tier variant tags. Let's tentatively keep it in, but perhaps ask around at meetings for use case and if they would rather have it modified / an additional system.

**Closed by dnil** 2023-01-16 15:39 UTC
Labels: enhancement, Cancer
