### ISSUE TITLE
pinned variant use wrong trancript to show HGVS description - BUG?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1846] opened 2020-03-31 13:19 UTC
See case 19025
at the case level note the n. numbering
![bild](https://user-images.githubusercontent.com/12525201/78030486-7713d880-7362-11ea-982a-8986e180b8f8.png)

If I select  the first pinned variant reported as RNASEH2A n.1134C>T
it look like this 
![bild](https://user-images.githubusercontent.com/12525201/78030594-9f033c00-7362-11ea-8676-3dc08f432875.png)
 with the correct HGVS description c.719C>T (only one transcript here where HGMD, HGNC and C mathc!)

I can see the n.1134C>T come from an ensemble transctipt
![bild](https://user-images.githubusercontent.com/12525201/78030793-f1dcf380-7362-11ea-9299-f53beb76df31.png)

Probably a bug , most pinned variants have been correct :)

**Comment by dnil** [comment] 2020-03-31 17:02
Hi there! Thanks for the watchful eye. The case is fairly old, and the hgvs string is now lifted directly off VEP, which was handled a bit differently in MIP back then, and is working for the recent cases, could you try rerunning the case before we dig any deeper? I have a hunch it may just resolve - otherwise it does seem reasonably likely we will have to go to ENSEMBL (which looks correct), VEP, or possibly MIP to find the cause?

**Comment by dnil** [comment] 2021-11-23 14:30
I'll close this for now as this particular thing has not popped up with more recent cases. Simply reopen if you decide to rerun and it remains an issue.

**Closed by dnil** 2021-11-23 14:30 UTC
Labels: question, Clinical Genomics Solna instance only
