### ISSUE TITLE
report problem

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#930] opened 2018-08-23 19:24 UTC
Hi guys!

todays errors message was: `werkzeug.routing.BuildError: Could not build url for endpoint 'report.report' with values ['level', 'panel_name', 'sample_id']. Did you mean 'cases.hpoterms' instead?`

This error did **not appear on our stage env** and only appeared on production.

Production does not have the latest packages and is still a python 3.5 env.
Stage has all latest packages and is a python 3.6 env.
Other information: if we want to pursue this issue, we can recreate the environment that produces this error, and test it on stage.

My suggestion however is to remake stage from scratch and I presume the problem will not persist anylonger. If that is the case, we can clone stage to prod and hopefully we will have a working and bleeding edge scout again.

Opinions? @northwestwitch @patrikgrenfeldt

**Comment by northwestwitch** [comment] 2018-08-23 20:03
The method call that triggers the error is not part of scout, but
chanjo-report. I think the problem is that chanjo report is either not
installed or it was removed from the production environment.

To install chanjo-report you should copy the relative line present in the
bash script of update-scout-stage into the bash script of
update-scout-prod.

But I agree that production environment should have updated packages,
included python 3.6!

**Comment by moonso** [comment] 2018-09-11 14:11
Closing this then since it is not a Scout issue

**Closed by moonso** 2018-09-11 14:11 UTC
