### ISSUE TITLE
Deleting users causes old assigned cases to show as inactive

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#2039] opened 2020-08-24 13:29 UTC
We suddenly have a bunch of old cases shown in the list of inactive. Most of these were archieved since a while back (several from 2018 and 2019), but might be one or two active cases hiding in there too... 
Have you done any updates or re-run any cases? 

/Sofie

**Comment by dnil** [comment] 2020-08-24 13:39
Hi! Hopefully this is more the matter for a ticket to production at CG  in Solna, but lets see! Could you give us a couple of case ids to work from? Thanks a bunch!

**Comment by dnil** [comment] 2020-08-24 13:44
Ooh, lets see: did you have a user leave recently, who was the sole assignee on these cases? I seem to recall a fix like that.  There might have been an issue with handling those in case the case was solved/archived, still assigned...

**Comment by dnil** [comment] 2020-08-24 13:45
The basic idea was to move active cases to inactive when the last user unassigned or was deleted..

**Comment by sofievonlanthen** [comment] 2020-08-24 13:46
Not the only assigne as some of them still have me or someone else assigned to the cases. 
Check out these ones: 91970140062 or 718701400035 (cust004)

**Comment by sofievonlanthen** [comment] 2020-08-24 13:47
But could def be the cases that our last member who left was assigned too. Need to check if any of these cases are supposed to be active.

**Comment by dnil** [comment] 2020-08-24 13:59
At least that is part of it. There is an issue with that update that will cause all the cases unassigned from to reset to inactive unless they are prioritized. Sorry about that - summer updates are dangerous. We may be able to help you with lists from a partial db dump from before your coworker was unassigned. Fortunately you dont have *that* many cases yet. 😅

**Comment by sofievonlanthen** [comment] 2020-08-24 14:01
Ok thanks for your help. Will go through them and re-archive cases.

**Comment by dnil** [comment] 2020-08-24 14:03
It's here if anyone has time to get started on it:
https://github.com/Clinical-Genomics/scout/blob/ab70f3eac5f9e3b91d49589ab255f17d042a7c6b/scout/adapter/mongo/case_events.py#L89
Intended behaviour is that status gets updated when the *last* user is unassigned from the case, not when any user unassigns. Also, only "active" cases change status; solved, archived, prioritised stay the same.

**Comment by dnil** [comment] 2020-08-24 14:11
@sofievonlanthen we can help you with a list of cases and probably previous status tomorrow - need to wrap up sth else now. 😊

**Comment by vwirta** [comment] 2020-08-24 16:38
@sofievonlanthen I can confirm that we removed access for one of your previous coworkers.
Send me an email if you need the name of the coworker

**Comment by dnil** [comment] 2020-08-24 16:44
Thank you @vwirta: I think we figured it out. And no way to know beforehand - it was an unexpected consequence. Possibly the first user removed after summer?

**Comment by vwirta** [comment] 2020-08-24 16:49
I think this was the first user @dnil , but checking with @emmser and @b4ckm4n to confirm

**Comment by northwestwitch** [comment] 2020-08-25 04:50
I can take this one!

**Comment by northwestwitch** [comment] 2020-08-25 05:05
When the last assignee actively removes him/herself as assignee from the interface, then it shows the option to inactivate the case or not:

![image](https://user-images.githubusercontent.com/28093618/91125089-3023d800-e6a1-11ea-9a59-b5fdf8ee4a8c.png)

 This error must occur when the user is removed from the command line. Sorry it's some changes I made in July: https://github.com/Clinical-Genomics/scout/pull/1981/files

**Comment by northwestwitch** [comment] 2020-09-01 09:18
Hi @sofievonlanthen, code-wise this is fixed now. Sorry for this problem! Do you want me to check the old status in a database backup and fix whatever I find different?

**Comment by sofievonlanthen** [comment] 2020-09-01 09:34
@northwestwitch No worries, glad it's fixed. I have gone through the cases and fixed it, archieved some and re-marked causatives for some.

**Comment by northwestwitch** [comment] 2020-09-01 09:38
Ok. closing this now then. Sorry again! 🙏

**Closed by northwestwitch** 2020-09-01 09:38 UTC
Labels: Easy, bug
