### ISSUE TITLE
HPO search not working

### ISSUE THREAD

**Issue by nicolelesko** [Clinical-Genomics/scout#257] opened 2016-02-19 08:20 UTC
The HPO search function is not working in family 15138.

**Comment by 4WGH** [comment] 2016-02-19 08:51
same in fam 16007

**Comment by moonso** [comment] 2016-02-19 08:59
In what way does it fail?

**Comment by 4WGH** [comment] 2016-02-19 09:05
when I click on ADD the HP:XXX number I typed in just diseappear.
the problem started this morning. It has been working for a whyle then stopped. Within the same family.
 
 
Michela -----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2016-02-19 09:58Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>Ärende: Re: [scout] HPO search not working (#257)
In what way does it fail?

**Comment by moonso** [comment] 2016-02-19 11:46
Ok I'm investigating this one

**Comment by moonso** [comment] 2016-02-19 13:31
They have updated Phenomizer, the software we use to build gene lists from hpo terms. The problem is that they now require username and password...
We are trying to find a solution to this.

**Comment by robinandeer** [comment] 2016-02-24 08:21
- [ ] update to v0.5
- [ ] put auth in config

**Comment by nicolelesko** [comment] 2016-02-25 13:24
HPO search not working in family 133.  I can add HP:XXX without any problem and the correct term and number comes up along with a list of genes connected to the term.  However, when I do a search in the clinical variants I get an error page.  This family has the research list open, can this have anything to do with it?

**Comment by robinandeer** [comment] 2016-02-26 07:29
For this particular case, the number of genes that phenomizer comes up with is too many for us to handle the normal way. We will implement a solution that works with any number of genes

**Comment by robinandeer** [comment] 2016-02-29 10:19
I've merged the fix into the prod branch ;)

**Closed by robinandeer** 2016-02-29 10:19 UTC
Labels: bug, Intermediate
