### ISSUE TITLE
Be explicit about relative / absolute paths config.yaml

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1394] opened 2019-10-17 12:29 UTC
Relative paths for vcf, bam are confusing. Absolute bam paths do not appear to work?

**Comment by northwestwitch** [comment] 2019-10-17 16:48
Being clear about how to fill in config files would certainly help. However I think that the issue of today with bam files was caused by a wrong key name -> bam_file instead of bam_path

**Comment by dnil** [comment] 2019-10-18 06:33
Quite right, #1397 so that doesn't happen again. 
But, my recollection was that strangeness did occur with relative paths that are not also correctly relative to your $PWD when loading. I'll try to replicate that.

**Comment by dnil** [comment] 2019-11-27 13:43
This is also a general issue with the way delayed file reads are handled. Consider e.g. batch loading research vcfs after some time.. It may have worked when loading each case yams originally, but now you will have to cd back to the each directory where the load was working relatively..

**Comment by northwestwitch** [comment] 2024-04-30 06:21
Closing this now that we have the Pydantic path validation in place.

**Closed by northwestwitch** 2024-04-30 06:21 UTC
Labels: enhancement, QualityOfLife
