### ISSUE TITLE
Dropdown menues too small now

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2662] opened 2021-05-25 08:16 UTC
Please reset the dropdown menu size to the previous setting :) It's very annoying and time consuming to have to scroll in the Gene panel menu and the Dismiss variant menu. Thank you <3

**Comment by NicoleCMMS** [comment] 2021-05-25 08:22
Agree with Ingegerd....this must be a bug?  The dropdown menu to get to issues is really strange!!!

**Comment by ielvers** [comment] 2021-05-25 08:25
The dropdown menu to get to issues is covered in this issue https://github.com/Clinical-Genomics/scout/issues/2660

For the other menues, I don't think it's a bug. The Variant tag menu is the same size as before. I would understand if the menues have to be a bit smaller as more options/gene panels are added but to only see four options is very inconvenient.

**Comment by northwestwitch** [comment] 2021-05-25 08:26
Thanks for reporting the issue and sorry for the inconvenience, we'll fix it ASAP. I'm closing this issue as it's a duplicate of #2660

**Closed by northwestwitch** 2021-05-25 08:26 UTC
