### ISSUE TITLE
panel export as pdf failed

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1067] opened 2018-11-12 09:23 UTC
I've tried to export the IEMv13 panel and for the following error 

504 Gateway Time-out

Michela

**Comment by northwestwitch** [comment] 2018-11-12 09:32
Hi! I think the problem is that for each gene it's searching if the gene is part of any other panels (those numbers on the right), and if there are thousands of genes it has to search for a long time, therefore the time out. We could try to optimize the algorithm but I don't know how much it will work when it comes to huge panels. 
I don't see any attachment, try a screenshot instead! Thanks! :)

**Comment by 4WGH** [comment] 2018-11-12 11:41
I can not attach or paste any file....
An issue in the issue?

o_O

**Comment by northwestwitch** [comment] 2018-12-11 09:53
This should be fixed by the new release so I'm closing this issue

**Closed by northwestwitch** 2018-12-11 09:53 UTC
Labels: Easy, bug
