### ISSUE TITLE
general report pdf - cut table

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1975] opened 2020-06-25 09:11 UTC
in fam 20101

the online page look like this (the table goes slightly outside the margin
![bild](https://user-images.githubusercontent.com/12525201/85690752-2c40fd00-b6d4-11ea-8a16-3bb9806560c2.png)

the pdf format is even worse (with the parenthood and coment going cut away from the page, lost of pink colour)
[20101_2020-06-25_scout.pdf](https://github.com/Clinical-Genomics/scout/files/4830215/20101_2020-06-25_scout.pdf)

**Comment by dnil** [comment] 2020-06-25 09:18
This looks like a duplicate of #1974?

**Closed by dnil** 2020-06-25 09:18 UTC

**Comment by 4WGH** [comment] 2020-06-25 09:23
yes sorry
