### ISSUE TITLE
Något lurt med "local observations"

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#2901] opened 2021-09-30 07:10 UTC
https://scout.scilifelab.se/cust002/F0040927/4e32767f3e98891f4689bcaaf6e05afe

<html>
<body>

Nr obs. | Nr homo. | Total nr.
-- | -- | --
1898 | N/A | 638

</body>
</html>

**Comment by northwestwitch** [comment] 2021-10-04 11:41
Hello! I see the problem here. This is a duplicate of #2169. The problem is that that number 638 is hardcoded in the scout page: https://github.com/Clinical-Genomics/scout/blob/e1e570d788bd113c498f1d6dbf3000cd57911476/scout/server/blueprints/variant/templates/variant/variant_details.html#L218

638 individuals were those populating one of the initial versions of the archive, but now there are more. Until we parse this number from somewhere (the VCF file) I suggest we hide that last column of that table, because it's only misleading!

**Comment by northwestwitch** [comment] 2021-10-04 12:11
I'm going to close this issue since it's duplicated, but I'll spend some time to find a solution today!

**Closed by northwestwitch** 2021-10-04 12:11 UTC
Labels: bug
