### ISSUE TITLE
Unable to create General report (dowloading of PDF)

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1289] opened 2019-08-26 06:20 UTC
I tried yesterday and today and I get the same error message:

"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Something wrong with my computer or something general??

**Comment by northwestwitch** [comment] 2019-08-26 06:27
We've received some error messages from the server at this regard, I'll take a look as soon as I'm at the office.

**Comment by northwestwitch** [comment] 2019-08-26 07:16
@ingkebil we are having some problems with scout that might be due to server settings, here's the error:

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='scout.scilifelab.se', port=443): Max retries exceeded with url: /reports/report?level=10&panel_name=OMIM-AUTO+%284.0%29&sample_id=ACC4407A1&sample_id=ACC5556A3&sample_id=ACC5556A4 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),))

How do we fix it?

**Comment by dnil** [comment] 2019-08-26 07:26
Perhaps call FL/file an issue with scilifelab IT again; pretty sure this is related to the certificate update issues Friday afternoon! 😊

**Comment by northwestwitch** [comment] 2019-08-26 08:53
It's definitely a server settings issue and I've been looking into the settings we have for scout and scout stage in the servers. I'm moving this issue there but I'll notify here when it is fixed.

**Comment by northwestwitch** [comment] 2019-08-26 08:58
Moved it here: https://github.com/Clinical-Genomics/servers/issues/179

**Comment by northwestwitch** [comment] 2019-08-26 09:04
> Perhaps call FL/file an issue with scilifelab IT again; pretty sure this is related to the certificate update issues Friday afternoon!

@ingkebil says we should disable the SSL certificates for scout and the settings are probably on our servers and we should be able to modify them

**Comment by ingkebil** [comment] 2019-08-26 09:41
yes, exactly. This way, IT can update the certificates without being dependent on an application. There is no need to encrypt traffic between localhost.

**Comment by northwestwitch** [comment] 2019-08-26 11:58
We are trying to fix it with the IT, I'll let you know as soon as we have news

**Comment by 1ctw** [comment] 2019-08-26 12:54
I see you are working to solve this. Just want to tell you that we at CMMS have the same problem...

**Comment by northwestwitch** [comment] 2019-08-26 12:56
> I see you are working to solve this. Just want to tell you that we at CMMS have the same problem...

Sorry for the inconvenience, hopefully we'll fix it soon

**Comment by ingkebil** [comment] 2019-08-26 13:10
Alright. We have now fixed the problem. Download ahead!

**Comment by dnil** [comment] 2019-08-26 13:13
Works!

**Comment by northwestwitch** [comment] 2019-08-26 13:13
Nice! Thanks @ingkebil !

**Closed** 2019-08-26 13:14 UTC
