### ISSUE TITLE
Can't login because address is not witelisted for admin user

### ISSUE THREAD

**Issue by golivag** [Clinical-Genomics/scout#732] opened 2018-02-06 08:56 UTC
Hi,
on a fresh installation of scout, when I try to login as an admin user I get:
"your email is not whitelisted, contact admin."
Regards

**Comment by patrikgrenfeldt** [comment] 2018-02-07 07:35
You may want to try to do the 'demo' mode to learn if scout is set up in
such a way that it can start at all.

Have you whitelisted your user via the scout CLI?

If unsure, you might try: 'scout --help' to learn how to use the CLI

BR
Patrik Grenfeldt
Clinical-Genomics


Den 6 feb. 2018 9:56 fm skrev "golivag" <notifications@github.com>:

**Comment by golivag** [comment] 2018-02-07 13:01
Hi Patrik,
thank you very much for your comment.
I already played with the demo version of scout.
I have added the user and made him admin and I can see it with:
scout view users
But I can't find any command to update the whitelist, on the documentation, the inline help of the cli and browsing the source code.
Can you please tell me how do I add a user to the whitelist by using the command line?
Thanks

**Comment by patrikgrenfeldt** [comment] 2018-02-07 14:13
Hi,
If you just change the demo user to have your own user info, can you then
log in into the demo setup?
BR
Patrik

Den 7 feb. 2018 2:01 em skrev "golivag" <notifications@github.com>:

**Comment by golivag** [comment] 2018-02-07 14:55
Hi Partrik,
the demo site and the development site are on two different databases; I can log in as clark.kent@mail.com in the demo site, but I cannot log in in the development site.
Do you want me to change the email field from clark.kent@mail.com to my address in the user collection of the demo database? Why?
Thank you very much for your help

**Comment by moonso** [comment] 2018-02-07 15:04
Hi, perhaps @robinandeer could say something about this

**Comment by patrikgrenfeldt** [comment] 2018-02-07 16:43
Ok, maybe that doesn't make sense in that case.
Do you know the status of your database connectivity from the Scout app?
Have you tried applying the authentication setup used in the demo setup?

BR
Patrik


Den 7 feb. 2018 3:56 em skrev "golivag" <notifications@github.com>:

**Comment by golivag** [comment] 2018-02-07 17:41
Since scout view users and institute works, I'm assuming there is no problem with the db connectivity. I don't use any particular setup in the demo I just use scout --demo serve, and this has no authentication: you only specify the email address and get in.

**Comment by patrikgrenfeldt** [comment] 2018-02-09 09:00
Yes, database connectivity seems fine, since you installed Scout for development I assume you have some development experience and can debug the auth of your user in Scout? I suggest that you might go for the auth-setup in the Demo setup unless you are working with real patient data or have any production setup.
Does it make sense?

**Comment by moonso** [comment] 2018-02-12 10:31
Hi @golivag , I've tried to replicate your problem without success.
Could you please repeat the commands you used to get this problem? 
How did you install scout, what version are you using?

**Comment by moonso** [comment] 2018-03-07 10:15
@golivag I'm closing this for now since there are many issues open. If the problem is still there please reopen with the information mentioned above.

**Closed by moonso** 2018-03-07 10:15 UTC

**Comment by patrikgrenfeldt** [comment] 2018-03-28 13:43
Did you check out the FAQ? http://www.clinicalgenomics.se/scout/faq.html
