### ISSUE TITLE
OMIM api-key requirement?

### ISSUE THREAD

**Issue by sirselim** [Clinical-Genomics/scout#1398] opened 2019-10-18 09:03 UTC
Apologies as this is probably a very basic question but has been the cause of a lot of frustration.

We're trying to import a couple of cases from our fairly standard pipeline (GATK4, genmod, VEP, dbNSFP). Most keys seem to be recognised however we're not getting mappings between the HGNC_id and gene symbols (i.e. only see the integers in Scout when looking at a loaded case).

After spending time looking at the parser and loader scripts it looks like the mappings are taken care of via OMIM, is this correct? We're unable to test this as we're not getting any response from the OMIM team for API access so we can't provide a key to Scout.

Is this assumption correct or is there potentially something else preventing correct assignment of gene symbols?

Thanks for your time and the great tool.

**Comment by northwestwitch** [comment] 2019-10-18 09:43
Hi and thanks for asking, the answer could be useful for other users as well. 

Yes, unfortunately you need a valid OMIM key to download the definitions from there. You'll need it also to visualize associated phenotypes, etc.

The steps you need to follow are described in this document: http://www.clinicalgenomics.se/scout/admin-guide/genes/

Please try loading the cases again after setting up the system using the OMIM key (I know by experience that it can take a while, but last time I applied for one I got it in a fairly short amount of time).

If it still does't work we can investigate more!

Kind regards,
Chiara

**Comment by dnil** [comment] 2019-10-18 10:03
Hi; yeah; thanks for the interest! 
The actual HGNC gene symbol to HGNC_ID mapping is from ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt, but that data is loaded together with the OMIM info. If this proves a lasting hassle, we could try to uncouple them. But having the OMIM API-connection is sweet, so don't give it up! Without phenotype info, triage isn't that efficient. Best regards!

**Comment by sirselim** [comment] 2019-10-18 20:02
Hi both, thanks for the confirmation. 

I agree that OMIM API connection is a really nice feature. What's the 'usual' wait time on getting access? From what I've read of other people's experience it's been same day (many within minutes). OMIM say 2 business days. We've been waiting a week now...

I'd be interested in the ability to uncouple to allow gene symbols to populate because as it stands without its a bit unfriendly. We have some clinical colleagues that are keen to have a play.

Happy to help out if useful!

**Comment by jdeligt** [comment] 2019-10-19 09:26
Hi @dnil and @northwestwitch, thanks for the quick responses. I'm working with Miles on a demonstration instance. I think it would be great to have this process more incremental. If I see you data models in Mongo you are looking into decoupling some of the data sources already. 

One thing that I found interesting is that you are 'coining' unique IDs for you transcripts/genes etc. Why not use the unique IDs from (for example) ensemble as the document/element _id s so that you 'automatically' enable cross refrencing in your variants? I.e. I tried a quick and dirty copy over of the demo hgnc / exon / transcript collections and that doesn't help. My gut feeling is that the id mismapping might be the cause of that.

OMIM annotation is great but not 'essential' and it does mean the usability of the platform is hampered by their speed/licencing requirements. Hence a more incremental approach would be great, i.e. bing able to add OMIM to the DB at the time when the person has access.

Any suggestions to 'hot-fix' this would be very welcome.

**Comment by northwestwitch** [comment] 2019-10-19 09:41
Assigning this to @moonso, that is the one with the beast insight over the gene loading process in the Scout team!

**Comment by northwestwitch** [comment] 2019-10-19 10:02
> One thing that I found interesting is that you are 'coining' unique IDs for you transcripts/genes etc. Why not use the unique IDs from (for example) ensemble as the document/element _id s so that you 'automatically' enable cross refrencing in your variants? I.e. I tried a quick and dirty copy over of the demo hgnc / exon / transcript collections and that doesn't help. My gut feeling is that the id mismapping might be the cause of that.

Just a quick comment about this: we are not using unique ids from for instance ensemble because for how the database is structured right now, they would not be unique. If you for instance take a random gene loaded with the demo data you'll see that it exists in 2 documents, one for each genome build, and they have the same ensemble id.

I'm not saying that the way we are populated this collection is the best ever, but so far it has been working fine for us.
Uncopling genes from phenotypes could be done but it would take a major restructuring of the software, which would take more time than waiting for the OMIM key I'm afraid..

**Comment by jdeligt** [comment] 2019-10-19 10:18
Thanks for that, I understand it would be a major rework and the problems of genome builds. With the new way of using contigs vs. chromosomes it is becoming increasingly prudent to decouple 'physical' data about a gene from it's meta data (phenotype, inheritance, etc.). We completely understand if this is something you can't adress right away but did want to flag it since we've been digging around and it struc me as sub-optimal/non future proof. 

Hope that @moonso has some tips or tricks to hot fix the linking while we wait for API clearance.

**Comment by dnil** [comment] 2019-10-19 12:24
OMIM were quick about keys last year; they might have had their attention elsewhere this week with ASHG happening.

As for incorrect and mostly nonexistent gene symbol mappings, they disappear as soon as you move away from the demo resources - that is OMIM is ok and you can load that EBI HGNC file.

Your eager clinicians will be much more positive if they can see disease names and inheritance patterns, so hang in there.

**Comment by moonso** [comment] 2019-10-19 15:52
Hi @jdeligt and @sirselim I tried to find your email addresses for a quick and dirty solution but it was not that easy. Feel free to send me a mail mans.magnusson@scilifelab.se

**Comment by moonso** [comment] 2019-10-19 16:02
Ok and the issues. I'm thinking about this suggestion you have to add OMIM at a later point. It sounds reasonable, I agree on that OMIM is not 'essential'. If there isn't too much work I can try to fix that.

Regarding the other question we have choosen to always use hgnc as a 'anchor', or what to call it, for all our genes. HGNC promises to maintain an updated map from hgnc id and hgnc symbol, and that each gene will always have ONE id. We have noticed that the symbols are quite flexible over time. However they do not maintain coordinates so here we have choosen to rely on ensembl and the mapping between hgnc -> Ensembl is also done by Ensembl.
To move exon -> transcript -> gene in scout one would need to use (build, ens_id), this is the best way to do it based on my research and for our needs but I'm willing to hear other opinions!

Happy to hear that you are trying out Scout 😃 , feel free to add stuff in the parse functions if it does not pick up some of your VCF-annotations and open PRs. We want scout to be flexible.

Best, Måns

**Closed** 2019-10-20 08:32 UTC
Labels: question

**Comment by dnil** [comment] 2019-10-20 08:37
Thanks to @moonso! I will leave you on master for now if that's ok. Holler if you want this hot-fixed and released. Feedback on master is much appreciated - it's not fully action tested yet. If you run into trouble with it you could always cherry pick this branch into a stable release. In any event, if you have time, we'd be happy for some notes back in a while on how you are doing!
