### ISSUE TITLE
Bug: Coverage report outputs different coverage

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/scout#3377] opened 2022-06-03 08:00 UTC
For following [internal case](https://scout.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq), when pressing "coverage report", below values are first shown.

<img width="861" alt="Screen Shot 2022-06-03 at 9 57 17 AM" src="https://user-images.githubusercontent.com/26735714/171813083-e905e190-9735-45c9-97ab-22d44c6691b0.png">

----------------

When copy pasting the URL in a new tab, different values are shown:

<img width="1020" alt="Screen Shot 2022-06-03 at 9 59 31 AM" src="https://user-images.githubusercontent.com/26735714/171813454-1a06082d-db1a-4049-8d0c-70ed62de16ae.png">

**Comment by dnil** [comment] 2022-06-03 08:50
Yeah, if I understand chanjo-report correctly, this is intended behaviour! Is this a problem in some system currently?

Note that the url does not contain information about what genes to search etc, so the gene panel changes (note the different number of transcripts e.g.). While there may be some residual issues with relying on the session object, in general, posting a request to an HTTP API with different options is expected to return different results.

**Comment by dnil** [comment] 2022-06-03 08:55
I'll close it for now @keyvanelhami, but just reopen with a use case if you have one that I'm not thinking about. For the most obvious, if you want another tab with the same report, right-click the original request button and choose open in new tab, and repeat as many times as needed. Or generate a pdf to look at as many times as you like. 😁

**Closed by dnil** 2022-06-03 08:55 UTC
Labels: question

**Comment by keyvanelhami** [comment] 2022-06-03 09:00
Thx @dnil, I justed wanted to check if this is the expected behavior or not =)

**Comment by dnil** [comment] 2022-06-03 09:01
> Thx @dnil, I just wanted to check if this is the expected behavior or not =) 

Du bara kollar så vi är med helt enkelt! 👍🏻😸
