### ISSUE TITLE
vcf 2 cytosure

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3784] opened 2023-01-30 08:41 UTC
Hej,

vcf analys ser mer skakligt/vågikt ut. på alla prover från 2023. 

Svårare att analyzera....
suggestions?

**Comment by dnil** [comment] 2023-01-30 10:20
Hi! Since vcf2cytosure v0.8 we are back to log scale, same as on the somatic side, and are also a little bit more careful about the N-region excludes from Tiddit coverage. This is arguably more representative of the data, but I agree it looks worse. We have a discussion going with MPe about this, and tentatively think updating the blacklist could help as a lot of the probes that fall to the "red" are at the edges of normal variation regions or actual N-sequence. What do you think?

**Comment by dnil** [comment] 2023-01-30 15:36
Just to keep the page easy to read I'm going to note this as a duplicate of https://github.com/NBISweden/vcf2cytosure/issues/58 and take the discussion there - but please chime in, I have not tested well enough yet to say what's the best action.

**Comment by dnil** [comment] 2023-01-30 15:37
Just to keep the page easy to read I'm going to note this as a duplicate of https://github.com/NBISweden/vcf2cytosure/issues/58 and take the discussion there - but please chime in, I have not tested well enough yet to say what's the best action.

**Closed by dnil** 2023-01-30 15:37 UTC
