### ISSUE TITLE
Causatives not found in the causative list

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1542] opened 2019-11-21 10:18 UTC
I cannot find the causative variant in ADK from case : https://scout.scilifelab.se/cust003/1
which is set as casuative on the case page.

However, it is not show here: https://scout.scilifelab.se/cust003/causatives

**Comment by northwestwitch** [comment] 2019-11-21 10:33
You're right, it's not there, bug!

**Comment by dnil** [comment] 2019-11-21 10:45
Is it in the events, and on a reasonably modern format? It’s very old.. I remember when MB was working on it. :D Possibly old enough to have been merged from an old no longer existing user...

**Comment by northwestwitch** [comment] 2019-11-21 11:19
This could be solved in a combo with #1532

**Comment by northwestwitch** [comment] 2019-11-21 13:41
I might have understood why the variant doesn't show among the causatives.
If you search in all events associated to that case, that variant, you 'll find these 4:

![image](https://user-images.githubusercontent.com/28093618/69342177-4496f800-0c6b-11ea-96dd-9145ac445957.png)

If you look at the associated "verbs" (will explain the event action):
- 2 variant pins
- 1 acmg classification
- 1 validation 

No **marked causative**. 

I don't know what happened to the event but it's not there. The problem is that it a marked causative event is required for a variant to be found and assigned to the causatives. Here is the code that finds the causatives:
![image](https://user-images.githubusercontent.com/28093618/69342812-a441d300-0c6c-11ea-8b4a-9c5771b11377.png)

We wrote the function this way (looking into "marked causative" events of the institute, instead of looking at the causatives field of each case of the institute) because it's faster. We might change it but it would need some index fixing.. Any suggestion??

**Comment by northwestwitch** [comment] 2019-11-21 14:17
Tried to "reset causative" for the variant and then "mark causative" it again and it shows among the causatives. It's not really a bug, but we should definitely check in how many cases this is happening. A custom script would do!

**Comment by northwestwitch** [comment] 2019-11-22 13:11
I'm going to work on this script now, let's see how many causatives we are missing!

**Comment by henrikstranneheim** [comment] 2019-11-22 13:18
What a cliffhanger!! Fingers crossed for very few 😄 !

**Comment by northwestwitch** [comment] 2019-11-22 14:59
Ok, I've got the number, do you want to guess?

**Comment by northwestwitch** [comment] 2019-11-22 15:05
1	cust003	15105	ea51a856847afc48446cdeea47dbbc9c
2	cust003	16123	206f689540587bf50a6b273bb9cfa045
3	cust003	16121	6a83f96e6017c22f29d3b8696120f58c
4	cust003	16120	88992bbe1a063df4524730a24bf214e7
5	cust003	15040	cfd18ce75692ed04e453deb1f3bf4683
6	cust003	208	27c01100a5c7686570e63141627f9067
7	cust002	F0005865	20bcd8dd9ff089381a68d3c16eb53647
8	cust002	F0005002	34b08f6265327ef8311ae3c053f5e36d
9	cust002	F0010946	f81dcc51b174856a7efd1650755ef635

**Comment by henrikstranneheim** [comment] 2019-11-22 15:13
Ok, great work. I will go in and manually set them again and then you can redo the test.

**Comment by henrikstranneheim** [comment] 2019-11-22 15:20
Done

**Comment by northwestwitch** [comment] 2019-11-22 15:33
I'll re-run the script later from home to confirm that i don't pick any one more!

**Comment by northwestwitch** [comment] 2019-11-22 18:12
The script didn't return any missing causative, you fixed them all @henrikstranneheim! 👍 
Closing the issue!

**Closed by northwestwitch** 2019-11-22 18:12 UTC
