### ISSUE TITLE
Not possible to open mtDNA report

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1352] opened 2019-10-02 06:12 UTC
It is not possible to open mtDNA report in the cases analyzed after update of Scout.

**Comment by northwestwitch** [comment] 2019-10-02 08:29
Checking this!

**Comment by northwestwitch** [comment] 2019-10-02 08:33
It's weird, it works well on stage. Error message is the following:
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 469, in mt_report
    n_files = controllers.mt_excel_files(store, case_obj, temp_excel_dir)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 366, in mt_excel_files
    sample_lines = export_mt_variants(variants=mt_variants, sample_id=sample_id)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/export/variant.py", line 138, in export_mt_variants
    for gene in variant.get('genes'):
TypeError: 'NoneType' object is not iterable

**Comment by northwestwitch** [comment] 2019-10-02 08:51
Reproduced on stage case: https://scout-stage.scilifelab.se/cust002/F0009130-validation.

**Comment by northwestwitch** [comment] 2019-10-02 09:42
The reason was that before all MT variants were in genes but now all MT variants are loaded, also those not in genes, but the code didn't take care of this. Fixed now. The change will be visible in the release of today.

**Closed** 2019-10-02 09:43 UTC
Labels: bug
