### ISSUE TITLE
Pileup viewer shows the wrong gene (IVG the correct one)

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#949] opened 2018-09-13 06:56 UTC
https://scout.scilifelab.se/cust003/18173/0cf4da80ff2e27c74280fc0914e27f59

If I look at the alignment with IGV it looks OK. Variant in STXBP1 
if I use Pileup I see the variant in another gene not in STXBP1 

The same issue occurs in other variants that I've random tested.

**Comment by northwestwitch** [comment] 2018-09-13 07:05
It might be due to a genome build issue. I'll look into it!

**Comment by northwestwitch** [comment] 2018-09-13 09:03
The problem is with the gene track, and apparently it is a known issue in Pileup (see here: https://github.com/hammerlab/pileup.js/issues/451). 
Before we spend time on fixing this by using a custom bigBed file I think we could discuss if we want to keep both viewers during next user meeting meeting, next week. What do you think?

**Comment by moonso** [comment] 2018-09-13 09:13
I think we are ready to drop pileup. As mentioned we can discuss it in the [user meeting](https://github.com/Clinical-Genomics/scout/issues/936). What do you think @4WGH ?

**Comment by henrikstranneheim** [comment] 2018-09-13 11:26
I am much in favor for IGV

**Comment by dnil** [comment] 2018-09-13 11:49
Concur! I rarely open pileup.js now. IGV.js needs colouring on InsertSizeAndOrientation like the standalone app, but that should be an issue to forward to them.

**Comment by moonso** [comment] 2018-10-01 06:17
Since this is a pileup issue I am closing this. If you want to proceed please go to hammerlab/pileup.js#451

**Closed by moonso** 2018-10-01 06:17 UTC
