### ISSUE TITLE
ClinVar - submission page freeze :(

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2473] opened 2021-03-24 14:53 UTC
There are some variants I can not submit as the submission page freeze :(

when i click the  
![image](https://user-images.githubusercontent.com/12525201/112330772-a1b81900-8cb8-11eb-9829-78e55fbc3bb2.png)

I send you the link of the 2 variants:

https://scout.scilifelab.se/cust003/19143/c8dce83866007943d3b2e4661290a8a2
https://scout.scilifelab.se/cust003/19091/4987140b170ac969865cfa93bf54fd2d

in both cases 19143 and 19091 there are 2 pinned variants per case but only one freeze :(

could you help me with this? I have an old memory that this has happend before but not how it was solved 
thanks :)

**Comment by northwestwitch** [comment] 2021-03-24 15:02
Hi, you remember well, this is not the first one. Last time we didn't find a solution. I couldn't reproduce the error when I uploaded the same case on our stage environment, so we said let's fix if it happens again. 
I'll try to take a look at it on the next few days

**Comment by 4WGH** [comment] 2021-03-24 15:03
ahahaha, today 2 times, and I'm still going on with more submission :)

**Comment by northwestwitch** [comment] 2021-03-24 15:05
> ahahaha, today 2 times, and I'm still going on with more submission :)

How many more do you have? 🙄

**Comment by 4WGH** [comment] 2021-03-24 15:12
All our causative in SCout ,
I take some every day ans submitt at the end of the week. 
👯

**Comment by 4WGH** [comment] 2021-03-24 15:19
ONE MORE
https://scout.scilifelab.se/cust003/18224

both MTR variants :(

**Comment by northwestwitch** [comment] 2021-03-24 15:20
Yes I kind of got the point! 😆

**Comment by northwestwitch** [comment] 2021-03-24 15:34
Woa I've just managed to add to your current submission the variants from https://scout.scilifelab.se/cust003/18224, moving this conversation to whatsapp

**Comment by northwestwitch** [comment] 2021-03-24 17:35
I think I've found the reason why these variants fail to submit. They are pinned together with another variant that has an invalid SNP ID: 
- case [19143](https://scout.scilifelab.se/cust003/19143) has the variant that doesn't work pinned with https://scout.scilifelab.se/cust003/19143/72f6fe76c1807ccbd6c31884e4574002 (wrong format)
- case [19091](https://scout.scilifelab.se/cust003/19091) has the variant that doesn't work pinned with https://scout.scilifelab.se/cust003/19091/123901ecd66fa1ac04a47b7258c0dad3 (wrong format)
- case [18224](https://scout.scilifelab.se/cust003) has 4 pinned variants, one is https://scout.scilifelab.se/cust003/18224/2efc0214fd13c0fcd2dedb8a1638f291 (wrong format)

What happens in the ClinVar form is:
- If you decide to submit all pinned variants, it allows you to correct the SNP field error in the problematic variant and the submission works
- If you decide to submit one variant at the time, the submit form still contains the other variants (included the one with the wrong SNP name) but they're hidden, and you can't correct the wrong field. So when you click on the submit button the validation fails but you have no way to fix it, because the wrong variant is not visible.

We'll fix this, but a quick workaround would be either:
- unpin the problematic variant, create the ClinVar submission and then pin it again.
- Submit all the pinned variants together.

Hope this made sense!

**Comment by 4WGH** [comment] 2021-03-25 07:25
super!

Good you can fix it and that I have a workaround solution 🙂


Thanks!



________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 24 mars 2021 18:35
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] ClinVar - submission page freeze :( (#2473)


I think I've found the reason why these variants fail to submit. They are pinned together with another variant that has an invalid SNP ID:

  *   case 19143<https://scout.scilifelab.se/cust003/19143> has the variant that doesn't work pinned with https://scout.scilifelab.se/cust003/19143/72f6fe76c1807ccbd6c31884e4574002 (wrong format)
  *   case 19091<https://scout.scilifelab.se/cust003/19091> has the variant that doesn't work pinned with https://scout.scilifelab.se/cust003/19091/123901ecd66fa1ac04a47b7258c0dad3 (wrong format)
  *   case 18224<https://scout.scilifelab.se/cust003> has 4 pinned variants, one is https://scout.scilifelab.se/cust003/18224/2efc0214fd13c0fcd2dedb8a1638f291 (wrong format)

What happens in the ClinVar form is:

  *   If you decide to submit all pinned variants, it allows you to correct the SNP field error in the problematic variant and the submission works
  *   If you decide to submit one variant at the time, the submit form still contains the other variants (included the one with the wrong SNP name) but they're hidden, and you can't correct the wrong field. So when you click on the submit button the validation fails but you have no way to fix it, because the wrong variant is not visible.

We'll fix this, but a quick workaround would be either:

  *   unpin the problematic variant, create the ClinVar submission and then pin it again.
  *   Submit all the pinned variants together.

Hope this made sense!

**Closed** 2021-03-25 09:23 UTC
