### ISSUE TITLE
Compound list contain variants in other genes, without stating the gene

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2714] opened 2021-06-15 15:06 UTC
I've only noticed this once so it's really not a big deal, but I still wanted to report it. You know how you've changed the compound list on the variant page to state which gene a variant belongs to, when a variant is annotated to several genes (a great improvement!)? In case 21169, variant https://scout.scilifelab.se/cust003/21169/294eaf9a3555f8a0c5d70f42cc5eed13, the variant is only annotated to one gene but I noticed that some of the variants in the compound list belong to other genes and this is not obvious from the compound list. The variant is in GSX2 but for example the top variant in the compound list (https://scout.scilifelab.se/cust003/21169/2ee503ee97d7bf80862dea25bd13e65f) is in LNX1 and other variants further down e.g. https://scout.scilifelab.se/cust003/21169/999c6a9c887ad30f0e1f88b36145ec3a are in PDGFRA. 

Again, not a big problem since I've only seen it once, but there's something weird going on.

**Comment by northwestwitch** [comment] 2021-06-17 06:12
Yes it looks weird! Thanks for reporting it, we'll look into it!

**Comment by northwestwitch** [comment] 2021-06-17 06:36
@moonso could you take a look at this one when you have time? You know how compounds are annotated and parsed in Scout better than me! Thanks!

**Comment by dnil** [comment] 2021-06-17 06:44
UCSC genome browser is your friend:
![Screenshot 2021-06-17 at 08 40 49](https://user-images.githubusercontent.com/758570/122345147-d0f0c600-cf47-11eb-8a69-b19e378191a6.png)
GSX2, LNX1, CHIC2 are all "contained" in transcripts of PDGFRA, which cause them to note as compounds for being in the same block. One can argue wether it is correct, but at least I think it is understood. Perhaps we should tame the compound parsing a bit to respect the VEP annotation? That way the compound relation would always be obvious from the transcript table.

**Comment by moonso** [comment] 2021-06-17 06:48
I guess that if you would investigate the compound variants they will be annotated to reside in multiple genes. If that is the case this is the intended behaviour.

**Comment by dnil** [comment] 2021-06-17 07:52
Right, and this is confirmed in the VCF compounds from GenMod. It does make sense, while it is perhaps not super intuitive for the user. I guess as @ielvers says it is not going to be very common that the region based compound annotation and VEP gene annotation differ. Both have merit, and by going to e.g. UCSC or ENSEMBL and zooming out a little the situation does become clear. I think we could close it with that, but suggestions for how to improve it would also be welcome. We could add like a little warning if the VEP annotation and region compound annotation do not agree. That would come at a page load cost though, as there are sometimes many compounds per variant.

**Closed** 2021-06-17 07:53 UTC
