### ISSUE TITLE
Case report pdf looks UGLY in production

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#919] opened 2018-08-20 11:00 UTC
I bet it has to do with the visualization libraries.. Another version in production than the ones on stage??

**Comment by northwestwitch** [comment] 2018-08-20 12:08
Hi @ingkebil, this issue might be due to the fact that the production environment doesn't have installed one or more libraries required by the library that exports html to pdf, weasyprint.  I'm specifically thinking about these two libraries: cairo and/or pango. It could also be that the libraries on production are older than those on stage. 
Could you take a look at it when you have time? I think this might be the issue because checking in the log I'm reading a lot of error and warning messages produced by weasyprint.
Here's the reference page for the library: https://weasyprint.readthedocs.io/en/stable/install.html
Thanks!

**Comment by ingkebil** [comment] 2018-08-20 20:10
I've downgraded cairocffi from 0.9.0 to 0.8.1 so far. There are a lot of differences between both environments, mostly because production has packages that are almost 2 months newer.

Can you link a page that opens a PDF report so I can test this out?

**Comment by ingkebil** [comment] 2018-08-20 20:11
I haven't had time to investigate: I presume the PDF report is generated on the fly, correct?

**Comment by dnil** [comment] 2018-08-20 20:17
Correct! I’m not behind firewall now, but clicking ”visualise report” to the top left on any case page to get to the html version and then selecting pdf download from the far right should reproduce it. Content is truncated.

**Comment by ingkebil** [comment] 2018-08-20 20:22
oooh. Well, that didn't get fixed with my downgrade. Will have to continue digging :)

**Comment by northwestwitch** [comment] 2018-08-21 08:44
Ok, here is a difference between stage (and my local copy) and prod: if I run "pip freeze", production env is lacking Flask_WeasyPrint, while stage has this line:
Flask-WeasyPrint==0.5

While re-installing scout on stage I noticed that it doesn't install  Flask-WeasyPrint, and says:
Requirement already satisfied: Flask-WeasyPrint in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages (from scout-browser==4.0.0)

But then if the package is there shouldn't it be seen by pip?

But then

**Comment by northwestwitch** [comment] 2018-08-21 09:08
HAA! That was the problem. If I launch a python shell from production and try to import Flask-WeasyPrint from there by typing "import flask_weasyprint" from there, it says:

ModuleNotFoundError: No module named 'flask_weasyprint'

Is there a way to force install a module even if python thinks it's there?

**Comment by northwestwitch** [comment] 2018-08-21 09:36
Well that didn't fix the PDF visualization :(

**Comment by ingkebil** [comment] 2018-08-21 10:27
... Meaning weasyprint is not in scout's requirements.txt? :)

wkr,
Kenny
--
Composed and sent on the road

**Comment by northwestwitch** [comment] 2018-08-21 10:51
It is!

**Comment by ingkebil** [comment] 2018-08-21 11:09
Sorry for all the stupid questions, I don't have access to a computer atm.

Clinical-db has 2 envs which can be seen as the production env: prod and
prod170926. As far as I remember, scout should be updated in the latter
which you can check in scout's update script.

It sounds as if you're upgrading with the `--no-deps` flag of pip, which
ignores the requirements.txt. is that correct?

wkr,
Kenny
--
Composed and sent on the road

**Comment by northwestwitch** [comment] 2018-08-21 11:27
It's ok! 
I'm using the "update-scout-prod.sh" bash command from clinical-db, which has no --no-deps flag, so it tries to install the Flask-WeasyPrint because it's in the requirements.txt file.  Since it finds Flask-WeasyPrint under /home/hiseq.clinical/miniconda/envs/prod/lib/python3.5/site-packages (from scout-browser==4.0.0) skips this step.

The thing is the bash file is activating the "prod" environment and not the "prod170926" one. See the content of the file:

#!/usr/bin/env bash

set -e

sh ./assert_user.sh hiseq.clinical
sh ./assert_host.sh clinical-db.scilifelab.se
sh ./confirm.sh 'This will install the latest version of scout (UI and CLI) on master in production, '

shopt -s expand_aliases
source ~/.bashrc

source activate prod

cd ~/SERVER/apps/scout/git/scout

# fetch recent changes from "master"
git pull
git rev-parse HEAD > current_version.txt

# install and update pip dependencies
pip install --editable .

# restart the Flask service
supervisorctl restart scout

**Comment by ingkebil** [comment] 2018-08-21 11:32
It would be nice not to c/p production scripts publicly ;)

wkr,
Kenny
--
Composed and sent on the road

**Comment by northwestwitch** [comment] 2018-08-21 11:36
Ok, but no passwords are involved. i just wanted to show you that everything is done on prod and not prod170926. I guess the script should be changed to activate the latter, right?

**Comment by ingkebil** [comment] 2018-08-21 11:47
Of course! Didn't want to have it turn into a habit ;)

To know which env is used, you have to check the supervisord.conf and
search for the scout section. Scout is run behind gunicorn which is
installed in a certain env. Scout needs to be installed in the same env.

wkr,
Kenny
--
Composed and sent on the road

**Comment by northwestwitch** [comment] 2018-08-21 11:59
Checked on supervisord.conf where the gunicorn is and found it under "prod", so we're good with bash file. You know what, I have a wreck of a computer at home with ubuntu mate. It's not the same distro as in clinical-db but I'll try to install everything on it and see what the problem might be from that.

**Comment by northwestwitch** [comment] 2018-08-21 12:01
And I'm removing the script from here! :)

**Comment by northwestwitch** [comment] 2018-08-21 12:08
Last message here for today because this issue is starting to look like a chat. 

I think we should change bash script and supervisord.conf and whatever else there is, to use "prod170926" for installing and running scout since in "prod" all libs are old, including the fact that python version id 3.5 in there, and not 3.6.

**Comment by ingkebil** [comment] 2018-08-21 19:42
so what action will come of this? Well, why don't we upgrade prod properly now?

**Comment by ingkebil** [comment] 2018-08-21 20:18
In any case: the issue itself it fixed )

Upgraded WeasyPrint itself, not Flask_WeasyPrint, and hopla!

**Closed by ingkebil** 2018-08-21 20:18 UTC

**Comment by northwestwitch** [comment] 2018-08-22 06:52
Nice! We should update the requirements to make it use the WeasyPrint version that works!
