### ISSUE TITLE
Problems in cancer scout after the last Scout uppdate

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#2826] opened 2021-08-30 07:33 UTC
Hi, after the last Scout update a few things are not working as they should in Cancer Scout:

- [x]  Links till “matching causatives from other cases” are not working, e.g.
https://scout.scilifelab.se/cust087/F0041371/cancer/504a020f0068b44557720d5c04c4da0e?cancer=yes

- [x] In the variant page, the gene information is not about the gene in which the mutation was found, e.g. CSDE1 - NRAS
https://scout.scilifelab.se/cust087/F0041371/cancer/91bdff58f63b755cb9ac067040311edb?cancer=yes (in the list with variants it was correctly listed as variant in NRAS)

- [x]  Link to COSMIC is not to the correct variant, e.g.:
Example A: https://scout.scilifelab.se/cust087/F0041371/cancer/504a020f0068b44557720d5c04c4da0e?cancer=yes
There are 3 well-described point mutations at this position, but the link does not include the one that was found in this patient even though it is reported in COSMIC (https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=42635557)

Example B:
https://scout.scilifelab.se/cust087/F0041371/cancer/6a2cb83e3f6bfbda297bb9625b55d58a?cancer=yes
COSMIC link to c.2601C>A instead of C>T --> non-synonymous change which is reported in hematological cases rather than the synonymous aa change that was found in the patient

**Comment by northwestwitch** [comment] 2021-08-30 09:40
Thanks both for reporting what looks like a bug, or several actually! We'll look into in ASAP!

**Comment by northwestwitch** [comment] 2021-08-30 09:47
I'll start working on the first problem, in case someone else wants to help! 😃

**Comment by northwestwitch** [comment] 2021-08-30 12:29
Checking the Cosmic link problem now. At the database level there are 3 cosmic IDs saved for the variant:

![image](https://user-images.githubusercontent.com/28093618/131338936-2fdbbdea-43db-44ff-9456-e8e9b6b8d692.png)

So it's not the VCF parsing, must be the rendering on the web page, I'll fix it!

**Comment by northwestwitch** [comment] 2021-08-31 05:55
You were right @hassanfa: Scout only showed the link to the first cosmic ID from the list of cosmic IDs associated to the variant. This was not introduced by the latest release, it has been like this all the time. This is now fixed by #2828.

**Comment by northwestwitch** [comment] 2021-09-03 08:34
This is also fixed, closing!

**Closed by northwestwitch** 2021-09-03 08:34 UTC
Labels: bug, question, Clinical Genomics Solna instance only

**Comment by dnil** [comment] 2021-09-03 10:16
> You were right @hassanfa: Scout only showed the link to the first cosmic ID from the list of cosmic IDs associated to the variant. This was not introduced by the latest release, it has been like this all the time. This is now fixed by #2828.

I have a vague recollection this was so by design: they were expected to be well linked between each other on the Cosmic side. But, showing all is all good. 👍
