### ISSUE TITLE
SCOUT opens Coverage window upon building "General report" (pdf)

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#2829] opened 2021-08-30 14:52 UTC
If I would like to download the general report - a "flik" for the coverage analysis is automatically opened. 

The general report is downloaded as usual but it is not necessary to open the coverage data...

**Comment by northwestwitch** [comment] 2021-08-31 11:05
What browser are you using? I can't reproduce it in chrome

**Comment by dnil** [comment] 2021-08-31 11:35
I have the same in Safari: it's the `target=_blank` for stopping the spinner.

**Comment by dnil** [comment] 2021-08-31 11:37
..but I agree I see Chrome closing the blank page when it is found empty!

**Closed** 2021-09-02 07:59 UTC
