### ISSUE TITLE
sorting of genelist

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/scout#220] opened 2015-12-08 19:56 UTC
sort genelist in alpabetical order to make it more easy to find gene of interest, or add option to sort in different ways

**Comment by moonso** [comment] 2015-12-08 19:59
There are several problems with the gene lists right now. The problem is solved but not merged.
We can check how hard it would be to sort the gene panels on name.

**Comment by vwirta** [comment] 2015-12-08 20:11
I meant sorting the content of the genelist, not the list of genelists

**Comment by moonso** [comment] 2015-12-08 20:13
Ok :+1:

**Closed** 2016-01-04 12:53 UTC
Labels: done, Easy, enhancement
