### ISSUE TITLE
Update nginx CORS policy

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/scout#2742] opened 2021-07-01 13:27 UTC
Update the nginx CORS policy for scout in **staging** to allow HTTP requests from **localhost** and ** https://scout-stage.web.app**
Also when running Scout in docker, it should be possible to call the endpoints from localhost:3000

**Comment by elevu** [comment] 2021-07-14 13:24
Note - OPTIONS calls are returning 302 when done from different origin

**Comment by elevu** [comment] 2021-08-25 07:34
Wait with this task until this is done https://github.com/Clinical-Genomics/scout-react/issues/52

**Comment by elevu** [comment] 2021-09-10 07:42
inspo: https://stackoverflow.com/questions/22181384/javascript-no-access-control-allow-origin-header-is-present-on-the-requested

**Comment by northwestwitch** [comment] 2021-09-14 12:04
After brainstorming meeting we understood that this problem is probably caused by the fact that the user is not authenticated in the scout-react demo setup. The easiest was to solve this would be to create a new endpoint in a scout view that would serve the scout-react app page as if it's coming from Scout. Basically in the same way as Scout is serving pages coming from Chanjo-report.

**Comment by elevu** [comment] 2021-09-14 14:28
https://scout-stage.web.app/cust000/phenotypes this page can be used for testing, it is calling https://scout-stage.scilifelab.se/. To see the error look into the console :)

**Comment by dnil** [comment] 2021-09-15 09:49
Ok, closing this with #2877. It activates CORS header answers from Flask directly from Scout, instead of adding them in NGINX. We may or may not want to keep it that way in the end, but react development is again enabled.

**Closed by dnil** 2021-09-15 09:49 UTC
Labels: blocking, Scout React
