### ISSUE TITLE
Some cases don't have the Diagnoses section

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4366] opened 2024-01-24 13:20 UTC
Check for instance [this one](https://scout-stage.scilifelab.se/cust000/F0050250-TN)

<img width="1476" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/72041f92-8c03-40a7-b3e3-6adcb52cf981">

In comparison with [this one](https://scout-stage.scilifelab.se/cust000/helpedfilly), which looks good:

<img width="1483" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/9e602e01-a84a-46a4-99dd-07988c1ec826">

**Comment by dnil** [comment] 2024-01-24 13:31
Ahem, isn't that by design since its a cancer case?

**Comment by dnil** [comment] 2024-01-24 13:31
```
          <!-- OMIM diagnoses-related code-->
        {% if not case.track == 'cancer' %}
```

**Comment by dnil** [comment] 2024-01-24 13:32
Closing for now, feel free to reopen if Im missing something! 😊

**Closed by dnil** 2024-01-24 13:32 UTC
Labels: bug
