### ISSUE TITLE
general report not working 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2927] opened 2021-10-15 13:49 UTC
I get this message, after 5 sec from clicking

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

tested in 2 fam 18217 and 21203

**Comment by dnil** [comment] 2021-10-15 13:51
Thank you! We are on it! Some other reports work, but there were changes to the general report endpoint to unify it with a future React version. This is what it looks like in the server log:

```
2021-10-15 15:48:15,143 - scout.server.app - ERROR: Exception on /cust003/18217/case_report [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
   return cors_after_request(app.make_response(f(*args, **kwargs)))
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 44, in decorated_function
   return render_template(template_name, **context)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
   ctx.app,
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
   rv = template.render(context)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
   self.environment.handle_exception()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
   reraise(*rewrite_traceback_stack(source=source))
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
   raise value.with_traceback(tb)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 1330, in top-level template code
   <td class="text-break"><strong>{{ comment.content }}</strong></td>
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/templates/report_base.html", line 14, in top-level template code
   {% block body %}
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 64, in block "body"
   {{ dismissed_panel() }}
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
   rv = self._func(*arguments)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/templates/cases/case_report.html", line 876, in template
   ({% for model in variant.genetic_models|sort %}
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/filters.py", line 348, in do_sort
   return sorted(value, key=key_func, reverse=reverse)
TypeError: 'NoneType' object is not iterable
```

**Comment by ielvers** [comment] 2021-11-03 09:57
Hi! We have come across a few more cases where we can't download the general report. So far 21181, 21217, 21096, 21218, 21106, 15042-2 (relatively recent rerun) are giving errors. Two independent people have tried. We could get a report for 15042-2 on Monday and 21106 yesterday. We can get reports for more recent cases, like 21279 and 21281.

**Comment by dnil** [comment] 2021-11-03 10:31
Ok, let's see if we can figure out what they have in common. I can also reproduce it for a few the ones I tested of those you mention, but attempts at reports from other random cases all work.

**Comment by dnil** [comment] 2021-11-03 10:34
Are they all reruns by any chance? There might be an issue with commented/dismissed variants that are now missing.

**Comment by dnil** [comment] 2021-11-03 10:46
```
2021-11-03 10:47:42,729 - scout.server.app - ERROR: Exception on /cust003/21181/case_report [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/utils.py", line 39, in decorated_function
    context = func(*args, **kwargs)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 213, in case_report
    data = controllers.case_report_content(store, institute_id, case_name)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 410, in case_report_content
    case_report_variants(store, case_obj, institute_obj, data)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 350, in case_report_variants
    decorated_variants.append(decorated_info["variant"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dnil** [comment] 2021-11-03 10:47
Tried removing a comment, a manual_rank and a dismissed from a local case, but report still works, so if so it is a particular type.

**Comment by dnil** [comment] 2021-11-03 12:47
It looks like this is working after the hotfix - right? Closing again, but just comment again if there are any remaining problems!

**Closed by dnil** 2021-11-03 12:47 UTC
Labels: bug
