### ISSUE TITLE
inheritance model in  OMIM not matching in two different boxes

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1875] opened 2020-04-14 16:17 UTC
https://scout.scilifelab.se/cust003/175/24f2e9801fa5161b059b5f106251173e

look at  OMIM box and Gene model box
the inheritance do not match. is the information collected from different sources?

![bild](https://user-images.githubusercontent.com/12525201/79248463-2d57e180-7e7c-11ea-9eca-f8911d38ee45.png)

**Comment by northwestwitch** [comment] 2020-04-15 06:14
Oh, that's not the expected behavior, I'll look into it! Thanks for reporting it @4WGH

**Comment by northwestwitch** [comment] 2020-04-15 06:59
Looking at the database at the gene level (hgnc_gene collection) the gene itself has inheritance model 'AR':

![image](https://user-images.githubusercontent.com/28093618/79305760-443a1a80-7ef4-11ea-8c9f-d4099f01bc48.png)

Here I see 2 weird things:
-  The gene inheritance model is 'AR' and also the OMIM inheritance is 'AR'. This is wrong because the inheritance models for this gene on OMIM is XLR:


![image](https://user-images.githubusercontent.com/28093618/79305983-a266fd80-7ef4-11ea-8e26-1bc6e464a8b1.png)


- The OMIM disease associated to this gene is also wrong. MEGALOBLASTIC ANEMIA 1 (OMIM 261100) has two other genes associated: CUBN and AMN, on chromosomes 10 and 14, respectively.

![image](https://user-images.githubusercontent.com/28093618/79306215-215c3600-7ef5-11ea-8cec-d1185d6c29da.png)


This bug might be associated to the other OMIM bug #1833, that we fixed immediately before Easter.
Could be that everything will be fixed by rebuilding the genes and phenotypes collections using the patched code. I'll try to see if it works locally!

**Comment by northwestwitch** [comment] 2020-04-15 07:59
Yes,  that's what I suspected. The problem is solved once the gene (and possibly the disease) collections are re-populated with the patched code.

See the difference, on the left is the gene built with the patched code, on the right the current gene from Scout database:

![image](https://user-images.githubusercontent.com/28093618/79312663-84eb6100-7eff-11ea-8aee-43020ff27a18.png)

I'll need to discuss with production team and find a good moment to updated the database, and immediately after this problem should be gone. I'll let you know when it's fixed!

Thanks again for bringing this to our attention! 👍

**Comment by northwestwitch** [comment] 2020-04-15 08:41
I'll update the database as soon as the Scout samples for this week are uploaded (tomorrow of Friday). I'll keep you updated!

**Comment by northwestwitch** [comment] 2020-04-18 05:49
I've just updated the definitions in Scout ( and Scout stage) databases.

Looks like the problem is solved:
- Omim diseases are correct for the gene
- Omim inheritance from in two panels is the same:

![image](https://user-images.githubusercontent.com/28093618/79629305-e2beb980-8148-11ea-8fb0-790c34a87f6f.png)

I'm closing the issue.

**Closed by northwestwitch** 2020-04-18 05:49 UTC
Labels: bug
