### ISSUE TITLE
PDF Delivery report is truncated

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2442] opened 2021-03-15 21:19 UTC
All the coverage qc reports that are delivered to Scout through deliver_report functionality are truncated and data from last column is unreadable. HTML is readable: https://scout.scilifelab.se/cust107/2017-00600-reprep

Reproduce:
1. Select a cancer case with a coverage qc report:
![image](https://user-images.githubusercontent.com/1086877/111222636-63499c80-85dc-11eb-97ee-02a3dcdee6d4.png)

2. Select PDF report:
![image](https://user-images.githubusercontent.com/1086877/111222657-6d6b9b00-85dc-11eb-8a05-36219acdc304.png)

**Comment by northwestwitch** [comment] 2021-03-16 08:03
Ah it took me a while to understand that I should look at the delivery report, I was looking at the coverage report and it was fine 😄 . I'll try to fix it ASAP

**Comment by northwestwitch** [comment] 2021-03-16 08:40
One thing I don't understand here is why the report named "Coverage and QC report", that you rightfully named `Coverage QC report` in this issue is loaded with the key `delivery_report` instead of `coverage_qc_report` in Scout. I think this is an unrelated problem that occurred upstream. If it's not a big deal it is fine, but otherwise we could fix it in 2 ways:

- Fix the process that creates the cancer case config file (cg?)
- Remove the coverage_qc_report key option from scout and have all cancer cases loaded with this report as `delivery_report`

**Comment by hassanfa** [comment] 2021-03-16 08:46
`cg` dev don't want to use `coverage_qc_report` for some reason that I didn't really understood. We can move this issue to `cg` and properly use `coverage_qc_report`?

In cancer analysis we will eventually use `coverage_qc_report` and `delivery_report`.

**Comment by hassanfa** [comment] 2021-03-16 08:50
Are you sure you want to fix PDF render based on a report that has different format? Will this affect rest of the delivery reports?

**Comment by northwestwitch** [comment] 2021-03-16 08:56
I've tried changing the key and it looks ugly also as a coverage_qc_report, so yes! I've opened [this issue in cg](https://github.com/Clinical-Genomics/cg/issues/1038)

**Comment by northwestwitch** [comment] 2021-03-16 08:57
It will require testing of the other reports as well, but I'll mostly fix the rendering document under `coverage_qc_report`

**Comment by dnil** [comment] 2021-03-16 09:07
Hi both! At the clinic today, but three things:
- the cancer qc report from Balsamic is currently the only delivery report available. Hence it will be used as such until there is a separation. We have talked at length with @Mropat @moonso among others, who strongly prefer it this way: I gave in, and this is very workable for now. Scout can use both, and the key as such will be useful later. Please sync with Balsamic dev for the cg issue ok, so there are actually two different files to upload first?
- Do you remember (@hassanfa) if you ever saw it rendered ok as pdf? I found an old temp dl:ed pdf from feb which also had the same issue.
- The pdf rendering library is sensitive to the html, and especially css, so what you rather may want to do is simplify esp some of the in-doc css from the html already in Balsamic.

**Comment by northwestwitch** [comment] 2021-03-16 09:16
Quick comment. I just don't see the point in naming something in the wrong way, especially knowing that it will eventually change in the future..

**Comment by moonso** [comment] 2021-03-16 09:17
If there is a delivery report and a coverage qc report we should of course upload both. We just need to know what tags to fetch the files from in Housekeeper.

> Quick comment. I just don't see the point in naming something in the wrong way, especially knowing that it will eventually change in the future..

there has been some confusion around this topic that is the answer to this question I suppose.

I can change so that the existing report get's uploaded as `coverage_qc_report` now.

**Comment by dnil** [comment] 2021-03-16 09:19
I agree in principle. It is named correctly in scout and balsamic. It works in CG as it is now, and there was a valid point from @moonso and @Mropat that the coverage_qc_report currently looks and functions very much like the rd delivery_report.

**Comment by hassanfa** [comment] 2021-03-16 09:21
> Hi both! At the clinic today, but three things:
> 
> * the cancer qc report from Balsamic is currently the only delivery report available. Hence it will be used as such until there is a separation. We have talked at length with @Mropat @moonso among others, who strongly prefer it this way: I gave in, and this is very workable for now. Scout can use both, and the key as such will be useful later. Please sync with Balsamic dev for the cg issue ok, so there are actually two different files to upload first?

Eventually we will have two different files yes. I don't think delivery report will replace coverage qc report. They serve different purpose.

> * Do you remember (@hassanfa) if you ever saw it rendered ok as pdf? I found an old temp dl:ed pdf from feb which also had the same issue.

No I only checked coverage_qc_report in Scout to render properly.

> * The pdf rendering library is sensitive to the html, and especially css, so what you rather may want to do is simplify esp some of the in-doc css from the html already in Balsamic.

I'm worried about the same thing as well.

**Comment by dnil** [comment] 2021-03-16 09:25
> > * Do you remember (@hassanfa) if you ever saw it rendered ok as pdf? I found an old temp dl:ed pdf from feb which also had the same issue.
> 
> No I only checked coverage_qc_report in Scout to render properly.

But they render via very similar looking code, so should be the same. If you saw at an ok pdf report there, it may "just" be some library update on the server. But lets see.

**Comment by hassanfa** [comment] 2021-03-16 09:25
> I agree in principle. It is named correctly in scout and balsamic. It works in CG as it is now, and there was a valid point from @moonso and @Mropat that the coverage_qc_report currently looks and functions very much like the rd delivery_report.

Well it is not delivery report.

**Comment by hassanfa** [comment] 2021-03-16 09:26
> Please stop implying that people don't listen to you @hassanfa , we are all trying to solve this in the best way possible.

I didn't imply anything. From DN's comment I see what's the reason now.

**Comment by northwestwitch** [comment] 2021-03-16 09:26
Keeping the discussion focused on the issue (please appreciate the effort! 😆  ) , we're still using that old version of flask_weasyprint, could be that!

**Comment by dnil** [comment] 2021-03-16 09:28
>What is confusing is that the coverage_qc_report has the tag delivery_report in housekeeper. So when there is another report available (maybe already now?) I'm not sure how to handle these tags. Should we rename the tags for the old report? If we keep the tag delivery_report for the coverage_qc_report in housekeeper, what tag should we need for the delivery_report etc etc.

Yeah, we actually had `coverage_qc_report` as the tag in the initial PR. No grudges here obviously. 😉 I don't think it is a big issue; as said, they are similar enough, and the content of a given report may change over time.

**Comment by moonso** [comment] 2021-03-16 09:31
Ok that sounds good. What is the conclusion? Do you want me to change so that the current report gets uploaded with the `coverage_qc_report` field or keep uploading it with the `delivery_report` field as it is now?

**Comment by hassanfa** [comment] 2021-03-16 09:32
Anyway, if the CSS layout is not proper in the report I can adopt it to the PDF renderer. QC report has a fixed table length, alternatively I can transpose QC report table to be vertical.

**Comment by dnil** [comment] 2021-03-16 09:35
> Ok that sounds good. What is the conclusion? Do you want me to change so that the current report gets uploaded with the `coverage_qc_report` field or keep uploading it with the `delivery_report` field as it is now?

Potato, potato? My humble suggestion would be to wait until Balsamic produces two files, then switch over in CG/Hermes at that point.

**Comment by dnil** [comment] 2021-03-16 09:36
(Or until Chanjo for cancer is operational, then CG can make the delivery report, just like for RD..)

**Comment by northwestwitch** [comment] 2021-03-16 09:36
> Anyway, if the CSS layout is not proper in the report I can adopt it to the PDF renderer. QC report has a fixed table length, alternatively I can transpose QC report table to be vertical.

This is likely the cause of the problem in rendering, the orientation of the PDF. The rare case delivery report is portrait and the cancer one panorama?

**Comment by hassanfa** [comment] 2021-03-16 09:41
Report template is here: https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/assets/report_template/balsamic_report.html#L54

If the change in Scout is too specific and limited to BALSAMIC, then I think it is better to change it BALSAMIC.

**Comment by moonso** [comment] 2021-03-16 09:43
Changed [here](https://github.com/Clinical-Genomics/cg/pull/1039) I'll merge that today so you know

**Comment by northwestwitch** [comment] 2021-03-16 09:47
@hassanfa if the cancer report will be under coverage_qc_report I can try to see if it can be rendered in landscape orientation by default. I'll let you know how it goes!

**Comment by dnil** [comment] 2021-03-16 10:02
Also in the template, the dl and dt width / margin fixes may need to be relaxed / changed? That does not seem to be a page orientation issue. In general, I would advise against this type of fixed sizes for everything, and let the engine render, but if some is fixed, it may be wise just to fix the remaining things..

**Comment by hassanfa** [comment] 2021-03-16 10:06
I see. I'll check later what I can do. Also: `https://www.bram.us/wordpress/wp-content/uploads/2017/01/css-is-awesome.jpg`

**Comment by dnil** [comment] 2021-03-16 10:07
That! Precisely that!

**Comment by northwestwitch** [comment] 2021-03-16 10:40
I've tested a bit following some suggestions in threads but with no success. I think it can be fixed by changing the css style

**Comment by hassanfa** [comment] 2021-03-16 10:45
`cg` PR to use coverage_qc tag and landscape doesn't help either, am I right?

**Comment by northwestwitch** [comment] 2021-03-16 10:49
I tested on the endpoint returning `coverage_qc_report` field.. No, but I can give it another try later

**Comment by hassanfa** [comment] 2021-03-16 10:51
I will look into this early next week, no worries.

**Closed** 2021-03-19 09:48 UTC
Labels: Cancer, Clinical Genomics Solna instance only, bug
