### ISSUE TITLE
IGV softclips

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#3298] opened 2022-04-06 10:18 UTC
Hi folks, is there a change in how softclips are visualised in new IGV-version?
We noticed (Hafdis) that some softclips, many, are shown as "NNNNN" rather than the exact sequence.
This will have negative impact on different levels; i.e. mapping breakpoint and understanding expansions.

**Comment by northwestwitch** [comment] 2022-04-06 10:47
Hi! As far as I know, soft-clips should be hidden in the alignment tracks. It is an optional parameter that is off by default: https://github.com/igvteam/igv.js/wiki/Alignment-Track.

We don't set the `showSoftClips` param to True in the code so they shouldn't show. But of course could be a problem in igv!

When you find one of these cases, could you check if there is a difference if you select and unselect  the `show soft clips` option in the alignment's settings?

<img width="271" alt="image" src="https://user-images.githubusercontent.com/28093618/161957994-4aab4cdf-5896-4c97-ae4d-3be806b3931b.png">

**Comment by dnil** [comment] 2022-04-06 10:49
Hi C! 

The issue is an abundance of reads showing softclipped N-bases, not nothing showing! After checking a few more, I'm starting to think it is indeed a change in IGV, but to the effect of actually showing the soft clip Ns, whereas they may not have been visible at all before. Here eg:

![Uploading Screenshot 2022-04-06 at 12.47.58.png…]()

**Comment by dnil** [comment] 2022-04-06 11:10
Can't reproduce on stage, do not see it in older non-rerun cases. Looking currently like a pipe change, but we'll be back when we know more.

**Comment by northwestwitch** [comment] 2022-04-06 11:16
I don't see it on prod either 😆, Which case are you looking at?

**Comment by dnil** [comment] 2022-04-06 11:21
Try valuedgrub eg!

**Comment by northwestwitch** [comment] 2022-04-06 11:29
Ah yes, I see them:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/28093618/161965052-12d894c1-e913-4ea6-865b-d5a2643605f7.png">

**Comment by dnil** [comment] 2022-04-06 11:51
By the looks of it (quality report excerpt below), this is rather an issue with a few recent sequencing runs in Solna. Closing the issue as a Scout one for now, since all seems well with it, but more to follow on other channels regarding the issue as such.
![Screenshot 2022-04-06 at 13 34 18](https://user-images.githubusercontent.com/758570/161968417-52f0aa06-45f5-46ab-89c5-5e3f4eef1661.png)

**Closed** 2022-04-06 11:52 UTC
