### ISSUE TITLE
Unable to parse HGNC ID due to presence of 'HGNC:' prefix

### ISSUE THREAD

**Issue by lfearnley** [Clinical-Genomics/scout#4397] opened 2024-02-02 04:44 UTC
I'm getting the following error loading a case  from nf-raredisease into a fresh install of Scout:

```
Traceback (most recent call last):
  File "/home/fearnleyl/scout/scout/adapter/mongo/variant_loader.py", line 719, in load_variants
    nr_inserted = self._load_variants(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/fearnleyl/scout/scout/adapter/mongo/variant_loader.py", line 436, in _load_variants
    parsed_variant = parse_variant(
                     ^^^^^^^^^^^^^^
  File "/home/fearnleyl/scout/scout/parse/variant/variant.py", line 175, in parse_variant
    parsed_transcripts = add_gene_and_transcript_info(parsed_variant, variant, vep_header)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fearnleyl/scout/scout/parse/variant/variant.py", line 565, in add_gene_and_transcript_info
    for parsed_transcript in parse_transcripts(raw_transcripts):
  File "/home/fearnleyl/scout/scout/parse/variant/transcript.py", line 27, in parse_transcripts
    transcript["hgnc_id"] = get_hgnc_id(entry)
                            ^^^^^^^^^^^^^^^^^^
  File "/home/fearnleyl/scout/scout/parse/variant/transcript.py", line 230, in get_hgnc_id
    return int(hgnc_id)
           ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'HGNC%3A7470'
```

Is this likely to be a raredisease issue, or a Scout one?

**Comment by dnil** [comment] 2024-02-02 06:35
Hi! Thank you kindly for reporting!As weird as it sounds, we dont run the nf rare-disease pipe in production yet. I imagine this is mostly a VEP version diff, in which case we will definitely update Scout to handle both formats. We'll take a look!

**Comment by dnil** [comment] 2024-02-02 13:08
I've asked for some VCF-files from the local nf-raredisease crew, and should get them next week. I'm kind of guessing we are timezone challenged here, but whenever it's convenient, perhaps you could post just the culprit line from your VCF? The one with the HGNC 7470. 

Ah, I wonder, it's from the MT; they were talking about using a different caller for the MT genome - perhaps they used a different consequence annotator than VEP as well! Anyway, sorry about the issue, and cheers for reporting!

**Comment by dnil** [comment] 2024-02-21 12:21
Lets remember to check if this is closed by fixing https://github.com/Clinical-Genomics/scout/issues/4445!

**Comment by lfearnley** [comment] 2024-02-22 01:50
Apologies for the delayed reply! I have hit some problems with nf-raredisease related to BWA-MEM2; I've forked nf-raredisease and implemented BWA instead. I'll follow up on this as I start getting the results for the cohort I'm working on.

**Comment by dnil** [comment] 2024-06-12 07:18
Hi again, while we don't have an exact test to reproduce your problem here, by the looks of it it was caused by the same as https://github.com/Clinical-Genomics/raredisease/issues/20 and should be fixed in recent versions of `raredisease`. Also the MT VCFs it produces by default can now be loaded separately by Scout (#4577). We'll close this for now, but feel very free to reopen should you run into it again! Cheers!

**Closed by dnil** 2024-06-12 07:18 UTC
Labels: nf-core/raredisease
